use_format_specific_options: false
default_highlighting: php
default_line_numbering: 1
use_highlight_string_for_php: false
enable_keyword_urls: true
decode_entities: false
css_mode: 1
code_container: '2'
tags: 'code blockcode'
tag_styles:
  1: 1
  2: 2
  8: 8
  4: 0
  16: 0
tab_width: 2
language:
  php:
    enabled: true
    tags: php
  cpp:
    tags: cpp
  java:
    tags: java
  css:
    enabled: true
    tags: css
  html5:
    enabled: true
    tags: html
  jquery:
    enabled: true
    tags: jquery
  mysql:
    enabled: true
    tags: mysql
  yaml:
    enabled: true
    tags: yaml
  twig:
    enabled: true
    tags: twig
_core:
  default_config_hash: 1jZtSc2CSiEBA45nbX0wMKFY3bmcilIwOBQCKFscK0U
