version: "2"

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - 7306:3306
    volumes:
      - mysqldata:/var/lib/mysql/data

  php:
    #image: drupal:9-fpm
    build: './docker/php'
    environment:
      MYSQL_HOSTNAME: mariadb
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_PORT: 3306
      MYSQL_DRIVER: mysql
    links:
      - mariadb:mysql
    volumes:
      - drupal-install:/opt/drupal

  nginx:
    image: nginx:latest
    links:
      - php
    ports:
      - '7080:80'
    volumes:
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - drupal-install:/opt/drupal
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: drupal
      NGINX_SERVER_ROOT: /opt/drupal/web

volumes:
  mysqldata: {}
  drupal-install: {}
